spring:
  profiles:
    active: development
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: chopper
    password: cyQk1052!)%@
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
socket:
  server:
    port: 8888
logging:
  level:
    kim:
      chopper: trace
  file:
    name: chat.log
---
spring:
  profiles: development
  datasource:
    url: jdbc:mariadb://chopper.kim:3307/chopper
---
spring:
  profiles: production
  datasource:
    url: jdbc:mariadb://localhost:3307/chopper
